spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    name: medicine
    url: jdbc:mysql://8.130.28.151:3306/medicine?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublickeyRetrieval=true&serverTimezone=UTC
    username: medicine
    password: medicine
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
      # Redis服务器端口,默认为6379.若有改动按改动后的来
    port: 6379
      #Redis服务器连接密码，默认为空，若有设置按设置的来
    password:
      jedis:
        pool:
          # 连接池最大连接数，若为负数则表示没有任何限制
          max-active: 8
          # 连接池最大阻塞等待时间，若为负数则表示没有任何限制
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springproje.bean
  global-config:
    db-config:
      id-type: auto
server:
  port: 8081

